sudo: required

language:
  - bash

services:
  - docker

before_install:  
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - sudo apt-key update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=1.11.1-0~precise
  # openshift
  - sudo apt-get install wget -y
  - sudo sed -i 's:DOCKER_OPTS=":DOCKER_OPTS="--insecure-registry 172.30.0.0/16 :g' /etc/default/docker
  - sudo mv /bin/findmnt /bin/findmnt.backup
  - sudo cat /etc/default/docker
  - sudo /etc/init.d/docker restart
  - wget https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-client-tools-v1.4.1-3f9807a-linux-64bit.tar.gz -O /tmp/oc.tar.gz
  - mkdir /tmp/ocdir && cd /tmp/ocdir && tar -xvvf /tmp/oc.tar.gz
  - sudo mv /tmp/ocdir/*/oc /usr/bin/

script:
  # run tests
  - docker version
  - oc version
  - oc cluster up
  - java -version
